# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: natural_join.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12natural_join.proto\"\x07\n\x05\x45mpty\"\x1e\n\x10RegisterResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x1e\n\x0eProcessRequest\x12\x0c\n\x04path\x18\x01 \x01(\t2L\n\x06Master\x12\'\n\x08Register\x12\x06.Empty\x1a\x11.RegisterResponse\"\x00\x12\x19\n\x05Start\x12\x06.Empty\x1a\x06.Empty\"\x00\x32*\n\x06Mapper\x12 \n\x03Map\x12\x0f.ProcessRequest\x1a\x06.Empty\"\x00\x32\x44\n\x07Reducer\x12\x1d\n\tPartition\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\x1a\n\x06Reduce\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'natural_join_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _EMPTY._serialized_start = 22
    _EMPTY._serialized_end = 29
    _REGISTERRESPONSE._serialized_start = 31
    _REGISTERRESPONSE._serialized_end = 61
    _PROCESSREQUEST._serialized_start = 63
    _PROCESSREQUEST._serialized_end = 93
    _MASTER._serialized_start = 95
    _MASTER._serialized_end = 171
    _MAPPER._serialized_start = 173
    _MAPPER._serialized_end = 215
    _REDUCER._serialized_start = 217
    _REDUCER._serialized_end = 285
# @@protoc_insertion_point(module_scope)
