# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wordcount.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwordcount.proto\"\x07\n\x05\x45mpty\"\x1e\n\x0eProcessRequest\x12\x0c\n\x04path\x18\x01 \x01(\t2*\n\x06Mapper\x12 \n\x03Map\x12\x0f.ProcessRequest\x1a\x06.Empty\"\x00\x32\x44\n\x07Reducer\x12\x1d\n\tPartition\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\x1a\n\x06Reduce\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wordcount_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=19
  _EMPTY._serialized_end=26
  _PROCESSREQUEST._serialized_start=28
  _PROCESSREQUEST._serialized_end=58
  _MAPPER._serialized_start=60
  _MAPPER._serialized_end=102
  _REDUCER._serialized_start=104
  _REDUCER._serialized_end=172
# @@protoc_insertion_point(module_scope)
